### ISSUE TITLE
libcloud missing database when upgrade b17 from 2.3.0 to 2.4.0

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1560]
#### Detailed description

when creating a vm after upgrade the environment we got the below error 

#### Steps to reproduce
Upgrade 2.3.0 to 2.4.0

pod sysncthing-01 was CrashLoopBackOff
```
syncthing-0                           1/2       CrashLoopBackOff   24         1h        10.244.2.93      b17-ctrl-03.b17

```
#### Relevant stacktraces
https://ENV_NAME/grid/error%20condition?id=5338f5e6-508e-bebb-f69b-3f57442d8f3b
```
ERROR IN RPC CALL createNamespace: AttributeError: 'OSISCMDS' object has no attribute '_incrementNamespaceId'. (Session:{u'roles': [u'node'], u'encrkey': u'', u'nid': 0, u'start': 1527224332, u'netinfo': [{u'ip': [u'127.0.0.1'], u'mac': u'00:00:00:00:00:00', u'cidr': [u'8'], u'name': u'lo', u'mtu': 65536}, {u'ip': [u'10.244.2.85'], u'mac': u'0a:58:0a:f4:02:55', u'cidr': [u'24'], u'name': u'eth0', u'mtu': 1500}], u'gid': 2003, u'passwd': u'Daxgi3m0g8', u'user': u'root', u'organization': u'myorg', u'id': u'2003_0_0_837ca7ba-69cb-4dc6-aea9-1c180f75f175'})
Data:{u'name': u'libcloud', u'template': None, u'incrementName': u'blob'}
```
#### Installation information
JumpScale
Core: tag: v7.4.0 (ae61629) 4/19/2018, 9:31:25 AM
Portal: tag: v7.4.0 (ac3419a) 4/18/2018, 2:53:21 PM
OpenvCloud
Core: tag: v2.4.0 (6ae7121) 5/4/2018, 11:05:58 AM
G8VDC: tag: v2.4.0 (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: tag: v2.4.0 (b32cfe8) 4/22/2018, 9:28:24 AM

**Comment by Pishoy** [comment]
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/629

**Comment by Pishoy** [comment]
note : i have create libcloud database and libvirtdomain collection but does not resolve it

**Comment by grimpy** [comment]
load this url once (with correct environment) to workaround this issue

https://ch-lug-dc01-001.gig.tech/system/ActorApi?group=libcloud#/libcloud__libvirt

**Comment by grimpy** [comment]
To workaround this for now:

```
ocl = j.clients.osis.getByInstance('main')
ocl.createNamespace('libcloud', template='blob')
```

**Comment by grimpy** [comment]
Should be fixed in 2.4.1
